version: '3.8'
services:
  hirc-two-run:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hirc-two-run
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - .:/workspace
      - /workspace/node_modules
    environment:
      - PORT=8000
    stdin_open: true
    tty: true 