name: Deploy to Cloud Run

env:
  SERVICE_NAME: seoulworld-two-run
  REGIONS: asia-northeast3

on:
  push:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          echo "REACT_APP_SUPABASE_API_URL=${{ secrets.REACT_APP_SUPABASE_API_URL }}" >> .env
          echo "REACT_APP_SUPABASE_ANON_KEY=${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}" >> .env
          echo "REACT_APP_SUPABASE_SLACK_FUNCTION_URL=${{ secrets.REACT_APP_SUPABASE_SLACK_FUNCTION_URL }}" >> .env

          export DOCKER_BUILDKIT=1
          docker build \
            -t asia-northeast3-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/hirc-repo/${{ secrets.DOCKER_IMAGE_NAME }}:latest \
            -t asia-northeast3-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/hirc-repo/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }} \
            .

          docker push asia-northeast3-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/hirc-repo/${{ secrets.DOCKER_IMAGE_NAME }}:latest
          docker push asia-northeast3-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/hirc-repo/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image asia-northeast3-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/hirc-repo/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }} \
            --platform managed \
            --region asia-northeast3 \
            --allow-unauthenticated \
            --max-instances 10 \
            --timeout 300 \
            --memory 512Mi \
            --cpu 1
